CREATE TABLE questions (
   QID INTEGER PRIMARY KEY AUTOINCREMENT,
   Stem VARCHAR(150) NOT NULL,
   Alt_A VARCHAR(50) NOT NULL,
   Alt_B VARCHAR(50) NOT NULL,
   Alt_C VARCHAR(50) NOT NULL,
   Alt_D VARCHAR(50) NOT NULL,
   Correct VARCHAR(3) NOT NULL
   );
